name: Publish to AWS Amplify
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Intial-Test:
    name: Code Analysis and Unit Test
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/Development.yml
  
  Dev-Publish:
    name: Pulblish to Dev Environment
    runs-on: ubuntu-latest
    steps:
    - name: Webhook to Amplify for Build
      run: >-
        curl -X POST 
        -d {} "https://webhooks.amplify.ap-southeast-1.amazonaws.com/prod/webhooks?id=0684e629-e16f-4ddf-85e5-307e7eb33c40&token=AVn0b5oyPvOoLWjZtV1ExRbCBoD0GleBQ8kKdxSOMU&operation=startbuild"
        -H "Content-Type:application/json"
  
