name: PR Testing & Dev Publish
on:
  pull_request:
    branches:
      - dev

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Intial-Test:
    name: Code Analysis and Unit Test
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/Development.yml
  
  Dev-Publish:
    name: Publish to Dev Environment
    uses: ./.github/workflows/Publish.yml
    secrets:
      env-path: ${{secrets.DEPLOY_DEV_PATH}}

  UAT:
    needs: [Dev-Publish, Intial-Test]
    name: 'Playwrright Testing'
    uses: ./.github/workflows/UAT.yml