name: Handling Pull Requests
on:
  pull_request:
    branches-ignore:
      - 'main'
    paths:
      - '**.cs'
      - '**.razor'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  UnitTest:
    name: Unit Test
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/Development.yml

  Analysis:
    name: CodeQL & Scantist
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/CodeAnalysis.yml
    secrets:
      SCANTISTTOKEN: ${{secrets.SCANTISTTOKEN}}

  Close-Pull:
    if: failure()
    needs: [UnitTest, Analysis]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Close Pull Test Failure
        run: gh pr close -R ${{github.repository}} --comment "Auto-closing the pull request! Tests have failed! Check and ammend before submitting new PR." ${{github.event.pull_request.number}} 
        env:
          GH_TOKEN: ${{ github.token }}
  
