name: Handling Pull Requests
on:
  pull_request:
    branches-ignore:
      - 'main'
    paths:
      - '**.cs'
      - '**.razor'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Tests:
    name: Code Analysis and Unit Test
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/Development.yml

  Close-Pull:
    if: failure()
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{github.event.pull_request.number}}
          comment: Auto-closing pull request
          delete-branch: False

        

  
