name: Publish - Test
on:
  push:
    paths:
      - '**.cs'
      - '**.razor'
    branches:
      - test

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event_name || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Intial-Test:
    name: Code Analysis and Unit Test
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/Development.yml
  
  Publish:
    name: Publish to Test Env
    uses: ./.github/workflows/Publish.yml
    secrets:
      env-path: ${{secrets.DEPLOY_TEST_PATH}}

  UAT:
    if: always()
    needs: [Publish, Intial-Test]
    name: 'Playwright Testing'
    uses: ./.github/workflows/UAT.yml
