name: Publish - Dev
on:
  push:
    branches:
      - 'dev'
    paths:
      - '**.cs'
      - '**.razor'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event_name|| github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Initial-Test:
    name: Code Analysis and Unit Test
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/Development.yml
  
  Release:
    needs: Initial-Test
    name: Release to Dev Env
    uses: ./.github/workflows/Publish.yml
    secrets:
        env-path: ${{secrets.DEPLOY_DEV_PATH}}
