name: Release
on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # Initial-Test:
  #   name: Code Analysis and Unit Test - (Uncessary)
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   uses: ./.github/workflows/Development.yml
  
  Release:
    if: github.event.pull_request.merged == true
    # needs: Initial-Test
    name: Release to Prod Environment
    uses: ./.github/workflows/Publish.yml
    secrets:
        env-path: ${{secrets.DEPLOY_MAIN_PATH}}
